DevHelp_DjangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="landing/shop.html"), name="home"),
    path('', include("settings.urls")),
    path('admin/', admin.site.urls),
    path('account/', include("account.urls"), name="account"),
    path('core/', include("core.urls"), name="core"),
    path('cart/', include("order.urls"), name="cart"),
    path('products/', include("products.urls"), name="products"),
    path('category/', include("category.urls"), name="category"),
    path('api/', include("api.urls"), name="api"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import *

app_name = "api"
urlpatterns = [
    # Account
    path('comments/list', CommentListView.as_view(), name='comment_list'),
    path('comments/create', CommentCreateView.as_view(), name='comment_create'),
    path('comments/details/<int:pk>', CommentDetailView.as_view(), name='comment_detail'),
    # Category
    path('categories/', CategoryListView.as_view()),
    path('categories/detail/<slug:url>', CategoryDetailView.as_view()),
    # Core
    path('users/', UserListView.as_view()),
    path('users/detail/<int:pk>', UserDetailView.as_view(), name="user_detail"),
    path('users/passwords/update/<int:pk>', ChangePasswordView.as_view(), name="change_password"),
    path('addresses/', AddressListView.as_view(), name="address"),
    path('addresses/detail/<int:pk>', AddressDetailView.as_view()),
    # Order
    path('orders/', OrderListView.as_view(), name="orders"),
    path('orders/detail/<int:pk>', OrderDetailView.as_view()),
    path('orderitems/', OrderItemListView.as_view(), name="orderitems"),
    path('orderitems/detail/<int:pk>', OrderItemDetailView.as_view(), name="orderitems_detail"),
    # Products
    path('products/', ProductListView.as_view(), name="products"),
    path('products/detail/<slug:url>', ProductDetailView.as_view()),
    path('discounts/', DiscountListView.as_view()),
    path('discounts/detail/<int:pk>', DiscountDetailView.as_view()),
    path('offcodes/', OffCodeListView.as_view()),
    path('offcodes/detail/<str:code>', OffCodeDetailView.as_view(), name="offcode_detail"),
    # Contact
    path('contacts/', ContactCreateListView.as_view(), name="contact"),
]

products/urls.py
from django.urls import path
from .views import ProductDetail, Products


urlpatterns = [
    path('', Products.as_view(), name="products"),
    path('<slug>', ProductDetail.as_view(), name="product"),
]

category/models.py
from django.db import models
from core.models import LogicalModel, TimeStampMixin
from django.utils.translation import gettext_lazy as _, get_language
from core.utils import *


class Category(LogicalModel, TimeStampMixin):
    name_fa = models.CharField(
        max_length=150,
        verbose_name=_("Category FA Name"),
        help_text=_("This is persian name category item"),
        unique=True,
    )
    name_en = models.CharField(
        max_length=150,
        verbose_name=_("Category EN Name"),
        help_text=_("This is english name category item"),
        unique=True,
    )
    image = models.ImageField(
        upload_to=Controllers.Image.img_renamer, null=True, blank=True,
        verbose_name=_("Category image"),
        help_text=_("This is image of category item")
    )
    url = models.SlugField(unique=True, verbose_name=_("Link"),
                           help_text=_("This is url or link of category -> /category/'url'"))
    description_en = models.TextField(
        default="This is test english category description", blank=True, null=True,
        verbose_name=_("English description"),
        help_text=_("This is english description for this category"))
    description_fa = models.TextField(
        default="این متن تست برای توضیحات بخش دسته بندی است", blank=True, null=True,
        verbose_name=_("Persian description"),
        help_text=_("This is persian description for this category"))

    @property
    def description(self):
        return self.description_en if get_language() == "en-US" else self.description_fa

    @property
    def name(self):
        return self.name_en if get_language() == "en-US" else self.name_fa

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name

products/models.py
from django.db import models
from core.models import LogicalModel, TimeStampMixin
from core.models import User
from category.models import Category
from django.utils.translation import gettext_lazy as _, get_language
from core.utils import *
from discount.models import Discount
from image.models import MultiImages


class ExtraProductManager(models.Manager):
    pass


class Product(LogicalModel, TimeStampMixin):
    title_en = models.CharField(
        max_length=150, verbose_name=_("English title"),
        help_text=_("This is english name of product item")
    )
    title_fa = models.CharField(
        max_length=150, verbose_name=_("Persian title"),
        help_text=_("This is persian name of product item")
    )
    short_description_en = models.CharField(
        max_length=400, verbose_name=_("English short description"),
        help_text=_("This is english short description of product item")
    )
    short_description_fa = models.CharField(
        max_length=400, verbose_name=_("Persian short description"),
        help_text=_("This is persian short description of product item")
    )
    description_en = models.TextField(
        verbose_name=_("English description"),
        help_text=_("This is english description of product item")
    )
    description_fa = models.TextField(
        verbose_name=_("Persian description"),
        help_text=_("This is persian description of product item")
    )
    price = models.PositiveIntegerField(verbose_name=_("Price item"), help_text=_("This is price item"))
    discount = models.ForeignKey(to=Discount, on_delete=models.SET_NULL, verbose_name=_("Discount"),
                                 help_text=_("This is discount for product item"), null=True, blank=True, default=None)
    image = models.OneToOneField(MultiImages, on_delete=models.CASCADE, verbose_name=_("Product Images"),
                                 help_text=_("This is images list of product item"))
    category = models.ForeignKey(
        to=Category, on_delete=models.CASCADE,
        verbose_name=_("Category of product"),
        help_text=_("This is category of product")
    )
    view_count = models.PositiveIntegerField(
        default=0, verbose_name=_("View counts"),
        help_text=_("This is count of view products")
    )
    is_offer = models.BooleanField(
        default=False, verbose_name=_("Offer"),
        help_text=_("This is status of offer product")
    )
    count_inventory = models.PositiveIntegerField(verbose_name=_("Count In Inventory"), default=1,
                                                  help_text=_("This is count of item in inventory"))
    count_buy = models.PositiveIntegerField(verbose_name=_("Count Of Buy"), default=0,
                                            help_text=_("This is count of buy item"))
    url = models.SlugField(verbose_name=_("Link"), default=Controllers.Product.url_creator, unique=True,
                           help_text=_("This is url or link name item -> /products/'url'"))

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    extra_objects = ExtraProductManager()

    @property
    def description(self):
        return self.description_en if get_language() == "en-US" else self.description_fa

    @property
    def short_description(self):
        return self.short_description_en if get_language() == "en-US" else self.short_description_fa

    @property
    def title(self):
        return self.title_en if get_language() == "en-US" else self.title_fa

    @property
    def final_price(self):
        return self.price - self.discount.final_discount(self.price) if self.discount else self.price

    @property
    def discount_count(self):
        return self.discount.final_discount(self.price) if self.discount else 0

    @property
    def viewed(self):
        self.view_count += 1
        self.save()
        return self.view_count

    def sell(self, count):
        self.count_inventory -= count
        self.count_buy += count
        if self.count_inventory <= 0:
            self.is_active = False
        self.save()

    def __str__(self):
        return self.title

products/views.py
from django.views.generic import ListView, DetailView
from account.models import Comment
from .models import Product


class Products(ListView):
    template_name = "landing/products.html"
    paginate_by = 8

    def get_queryset(self):
        return Product.objects.get_active_list().filter(is_offer=False)

    def get_context_data(self, *args, object_list=None, **kwargs):
        kwargs["counter"] = Product.objects.count()
        return super().get_context_data(object_list=object_list, **kwargs)


class ProductDetail(DetailView):
    template_name = "landing/product_detail.html"
    model = Product
    slug_field = "url"

    def get_context_data(self, **kwargs):
        kwargs["comments"] = Comment.objects.filter(product__id=self.object.id, is_accept=True, reply__isnull=True)
        return super().get_context_data(**kwargs)

templates/landing/about.html
{% extends "landing/base.html" %}
{% load i18n %}
{% block title %}{% trans "About us" %}{% endblock %}
{% load static %}
{% block offer %}{% endblock %}
{% block body %}
    <div class="mb-8 mt-4 text-white rounded-lg overflow-hidden max-w-screen-lg w-11/12 mx-auto bg-black bg-opacity-20 text-lg">
        <div style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=Dehaqan+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe></div>
        <div class="p-5">
            <p><i class="gb gb_phone gb_r270 ml-1"></i> {% trans "Phone number" %} : {{ site.phone }}</p>
            <p class="my-6"><i class="gb gb_home ml-1"></i>{% trans "Address" %} : {{ site.address }}</p>
            <p class="">{{ site.description }}</p>
            <p class="mt-6">{{ site.about }}</p>
        </div>
    </div>
{% endblock %}
{% block click_item %}{% endblock %}a

templates/landing/base.html
{% load static %}
{% load i18n %}
{% load render_partial %}
{% get_current_language as lang %}
<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
    <title>{{ site.full_title }} | {% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="theme-color" content="#34373F">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static "img/favicon.ico" %}">
    <!-- SEO - Meta tags -->
    <meta property="og:title" content="{{ site.full_title }}">
    <meta property="og:url" content="{{ site.url_full }}">
    <meta property="og:image" content="{{ site.large_logo.url }}">
    <!-- header refrense -->
    {% include "landing/layout/_Head.html" %}
    <!-- external header -->
    <!-- language style customizer: -->
    {% if lang == "en-US" %}
        <style>
            * {
                direction: ltr !important;
            }

            *:not(center) {
                 text-align: left;
            }

            center , center * {
                text-align: center;
            }

            i {
                margin-left: 5px;
                margin-right: 5px;
                margin-top: -3px;
            }

            .Vazir, .Vazir *:not(i) {
                font-family: sans-serif !important;
            }

        </style>
    {% endif %}
    {% block extra_head %}{% endblock %}
</head>
<body>
<!-- haeder box -->
{% render_partial "partial_header" %}
<!-- search box -->
{% render_partial "partial_search" %}
<!-- best category -->
{% block category_list %}
    {% render_partial "partial_category" %}
{% endblock %}
<!-- nav -->
{% block nav %}
    {% render_partial "partial_nav" %}
{% endblock %}
<!-- offer shop -->
{% block offer %}
    {% render_partial "partial_offer" %}
{% endblock %}
<!-- body content -->
<div id="body_block" style="min-height: 10vh;">
{% block body %}{% endblock %}
</div>
<!-- click content -->
{% block click_item %}
    {% include "landing/layout/_ClickItem.html" %}
{% endblock %}
<!-- footer content -->
{% render_partial 'partial_footer' %}
<!-- footer refrense -->
{% include "landing/layout/_Foot.html" %}
<!-- extra footer -->
{% block extra_foot %}{% endblock %}
</body>
</html>

templates/landing/categories.html
{% extends "landing/base.html" %}
{% load i18n %}
{% block title %}{% trans "Categories" %}{% endblock %}
{% get_current_language as lang %}
{% block offer %}{% endblock %}
{% block category_list %}{% endblock %}
{% block body %}
    <center class="w-11/12 mx-auto max-w-screen-lg pb-2 mb-8 rounded-full border-b-2 border-gray-400"><h1
            class="text-center text-white text-shadow-md text-4xl irsans-b">{% trans "Categories" %}</h1></center>
    <div class="mt-4 mb-8 max-w-screen-lg w-11/12 mx-auto grid gap-8 grid-cols-1 sm:grid-cols-3 md:grid-cols-4"
         style="min-height: 50vh;">
        {% if object_list %}
            {% for i in object_list %}
                <a href="{{ i.url_full }}" class="relative rounded-lg col-span-1">
                    <div class="relative">
                        <img src="{{ i.image.url }}" alt="{{ i.name_en }}"
                             class=" border-8 border-red-500 rounded-t-lg">
                        <h3 class="yekan-b absolute bg-black trs-all-300 bg-opacity-70 text-white text-2xl sm:text-sm md:text-lg lg:text-2xl pr-2 pl-5 sm:py-1 lg:py-2 py-2 bottom-0 right-0 rounded-tl-3xl">{{ i.name }}</h3>
                    </div>
                    <p class="p-4 bg-black bg-opacity-40 bg-strip-sm  text-justify text-white sm:text-sm rounded-b-lg">{{ i.description }}</p>
                </a>
            {% endfor %}
            <section class="container col-span-1 sm:md:col-span-3 md:col-span-4 text-center Vazir">
                <nav class="pagination block">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" class="prev">&laquo;</a>
                    {% else %}
                        <a disabled="disabled">&laquo;</a>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <span>{{ i }}</span>
                        {% else %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="next">&raquo;</a>
                    {% else %}
                        <a disabled="disabled">&raquo;</a>
                    {% endif %}
                </nav>
            </section>
        {% else %}
            <center class="col-span-4"><h1
                    class="text-gray-500 font-bold">{% trans "There is no item to display!" %}</h1></center>
        {% endif %}
    </div>
{% endblock %}
{% block click_item %}{% endblock %}

templates/landing/contact.html
{% extends "landing/base.html" %}
{% load i18n %}
{% block title %}{% trans "Contact us" %}{% endblock %}
{% load static %}
{% block offer %}{% endblock %}
{% block body %}
    <div class="mb-8 mt-4 text-white rounded-lg max-w-screen-lg w-11/12 mx-auto bg-black bg-opacity-20 text-lg">
        <div class="pt-2 pb-1 px-5">
            <form class=" mx-auto pt-4 mb-6">
                <input type="hidden" hidden name="user" value="{{ user.id }}">
                <input type="text" helper_name="{% trans "First name and Last name" %}" placeholder="{% trans "Please enter your first and last name" %}" name="name"
                       value="{{ user.get_full_name }}"
                       class="block w-full py-4 rounded-md px-3 bg-black bg-opacity-30 mb-4">
                <input type="tel" helper_name="{% trans "Phone number" %}" placeholder="{% trans "Please enter your email (optional)" %}" name="phone"
                       value="{{ user.phone }}"
                       class="block w-full py-4 rounded-md px-3 bg-black bg-opacity-30 mb-4">
                <input type="email" helper_name="{% trans "Email" %}" placeholder="{% trans "" %}" name="email"
                       value="{{ user.email }}"
                       class="block w-full py-4 rounded-md px-3 bg-black bg-opacity-30 mb-4">
                <textarea name="msg" helper_name="{% trans "Message" %}" placeholder="{% trans "Please enter your message" %}" cols="30" rows="10"
                          class="block w-full py-4 rounded-md px-3 bg-black bg-opacity-30 mb-4"></textarea>
                <div class="grid grid-cols-2 gap-2 ltr">
                    <input type="reset" value="{% trans "Clear" %}"
                           class="text-center py-3 rounded-md trs-all-300 bg-yellow-600 hover:bg-yellow-700  text-shadow-md cursor-pointer">
                    <button onclick="MessageSender($(this))" type="button"
                            class="text-center py-3 rounded-md trs-all-300 bg-green-600  hover:bg-green-700 text-shadow-md cursor-pointer">{% trans "Send" %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block click_item %}{% endblock %}
{% block extra_foot %}
    <script>
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                }
            }
        });

        // utility function
        function getFormData(data) {
            let unindexed_array = data;
            let indexed_array = {};

            $.map(unindexed_array, function (n, i) {
                indexed_array[n['name']] = n['value'];
            });

            return indexed_array;
        }

        function MessageSender(el) {
            const form = el.parent().parent()
            const data = form.serializeArray();

            $.ajax({
                url: '{% url "api:contact" %}',
                type: 'POST', contentType: 'application/json',
                data: JSON.stringify(getFormData(data)),
                error: function (xhr, status, error) {
                    let err = JSON.parse(xhr.responseText);
                    let _text = ""
                    $.each(err, function (k, v) {
                        let key = $("[name=" + k + "]").attr("helper_name") + " : "
                        _text += key + v + "<br>"
                    })

                    Swal.fire({
                        icon: 'error',
                        title: '{% trans "Control the inputs!" %}',
                        html: _text,
                        showConfirmButton: false, timer: 8500, timerProgressBar: true,
                    })
                }
            }).done(function () {
                Swal.fire({
                    icon: 'success',
                    title: '{% trans "Your message has been successfully sent!" %}',
                    showConfirmButton: false, timer: 3500, timerProgressBar: true,
                })
            })
        }
    </script>
{% endblock %}

templates/landing/final.html
{% extends "landing/base.html" %}
{% load mathfilters %}
{% load i18n %}
{% block extra_head %}
    <style>
        .selected {
            background: #059669;
        }

        .selected:hover {
            background: #027653;
        }
    </style>
{% endblock %}
{% block title %}{% trans "Pay" %}{% endblock %}
{% block offer %}{% endblock %}
{% block body %}
    <div class="main relative">
        <div class="trs-all-300 grid grid-cols-1 sm:grid-cols-2 relative max-w-screen-lg relative mx-auto w-11/12 gap-8 rounded-md p-8 bg-black mt-16 bg-opacity-40 mb-8 z-10 filter ">
            <h3 class="text-center absolute mx-auto inset-x-0 -top-8 text-shadow-md">
                    <span class="irsans-b text-xl bg-black bg-opacity-40 rounded-t-md border-t border-r border-l border-black py-1 px-8 text-white">
                    <i class="gb gb_assignment ml-3"></i>{% trans "Address selection and payment" %}</span>
            </h3>
            <div class="text-white col-span-2">
                <h2 class="text-center irsans-b pb-4 text-shadow-md border-b text-xl border-white border-opacity-20">{% trans "Addresses" %}
                    : </h2>
                <a href="{% url "address" %}"
                   class="text-right block irsans-b py-4 mb-6 text-yellow-400 hover:text-yellow-600 blink trs-all-300">{% trans "You can manage your addresses in the user profile section! - Enter the addresses section" %}</a>
                <div class="grid grid-cols-2 gap-4 sm:gap-8">
                    {% if addresses %}
                        {% for address in addresses %}
                            <div id="{{ address.id }}"
                                 class="address Vazir bg-gray-700 rounded-md grid grid-cols-2 p-4 gap-4 cursor-pointer hover:bg-gray-600 trs-all-300">
                                <p class="">{% trans "Country" %} : {{ address.country }}</p>
                                <p class="">{% trans "City" %} : {{ address.city }}</p>
                                <p class="">{% trans "Postal code" %} : {{ address.postal_code }}</p>
                                <p class="">{% trans "No" %} : {{ address.no }}</p>
                                <p class="col-span-2">{% trans "Address" %} : {{ address.address }}</p>
                            </div>
                        {% endfor %}
                    {% else %}
                        <center class="col-span-2">
                            <h1 class="text-3xl text-gray-400 irsans-b text-shadow-md">{% trans "There is no address to display!" %}</h1>
                        </center>
                    {% endif %}
                </div>
            </div>
            <div class="text-white relative col-span-1">
                <span class="block irsans-b text-lg text-center">{% trans "Final price" %} : </span>
                <span class="block Vazir text-lg text-center text-4xl font-bold mt-8"><span
                        id="final">{{ order.final_price|sub:order.total_offcode }}</span> {% trans "Toman" %}</span>
            </div>
            <div class="text-white relative col-span-2 sm:col-span-1">
                <button type="button" id="final_cart" disabled="disabled"
                        class="cursor-not-allowed rounded-lg py-8 bg-yellow-600 border-b-2 border-yellow-700 irsans-b text-2xl block text-center hover:bg-yellow-800 trs-all-300 w-full">{% trans "Pay" %}</button>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_foot %}
    <script>
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                }
            }
        });

        $('.address').click(function () {
            $("#final_cart").removeAttr("disabled").removeClass("cursor-not-allowed")
            $(this).addClass("selected")
            $('.address').not(this).removeClass("selected")
        })

        $("#final_cart").click(function () {
            if (!($(this).attr("disabled") || $(this).hasClass("cursor-not-allowed"))) {
                $.ajax({
                    url: "{% url "final-cart" %}",
                    type: "POST",
                    data: {'address_id': $(".address.selected").attr("id")},
                }).done(function () {
                    Swal.fire({
                        icon: 'success',
                        title: '{% trans "Your order has been registered!" %}',
                        text: '{% trans "You will be redirected to your arrival page." %}',
                        showConfirmButton: false, timer: 3500, timerProgressBar: true,
                    })
                    setTimeout(function () {
                        window.location.replace("{% url "recepie" order.recepie_id %}")
                    }, 3600)
                })
            }
        })
    </script>
{% endblock %}
{% block click_item %}{% endblock %}

templates/landing/products.html
{% extends "landing/base.html" %}
{% load i18n %}
{% block title %}{% trans "Products" %}{% endblock %}
{% get_current_language as lang %}
{% block body %}
    <div class="mt-4 mb-8 max-w-screen-lg w-11/12 mx-auto grid gap-4 grid-cols-1 sm:grid-cols-3 md:grid-cols-4"
         style="min-height: 50vh;">
        {% if counter %}
            {% for i in object_list %}
                <a href="{% url "product" i.url %}" class="relative rounded-lg block">
                    <div class="relative">
                        <img src="{{ i.image.default }}" alt="{{ i.title_en }}"
                             class=" border-8 border-red-500 rounded-t-lg">
                        <h3 class="yekan-b absolute bg-black trs-all-300 bg-opacity-70 text-white text-2xl sm:text-sm md:text-lg lg:text-2xl pr-2 pl-5 sm:py-1 lg:py-2 py-2 bottom-0 right-0 rounded-tl-3xl">{{ i.title }}</h3>
                    </div>
                    <p class="p-4 bg-black bg-opacity-40 bg-strip-sm  text-justify text-white sm:text-sm">{{ i.short_description }}</p>
                    <div class="bg-black relative bg-strip-sm bg-opacity-30 text-center p-4 rounded-b-lg">
                        <span class="absolute text-2xl sm:text-sm md:text-lg right-4 {% if lang != "en-US" %}Vazir{% endif %} {% if i.discount %}md:bottom-3 bottom-3{% else %}md:bottom-6 bottom-7{% endif %} text-gray-400">
                        <span class="block">{% trans "Toman" %}</span>
                            {% if i.discount_count %}
                                <span class="line-through">{{ i.price }}</span>
                            {% endif %}
                        </span>
                        <b class="text-5xl sm:text-2xl md:text-4xl mt-2 sm:mt-0 block text-left text-pink-700 text-shadow-md {% if lang != "en-US" %}Vazir{% endif %}">{{ i.final_price }}</b>
                    </div>
                </a>
            {% endfor %}
            <section class="container col-span-1 sm:md:col-span-3 md:col-span-4 text-center Vazir">
                <nav class="pagination block">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" class="prev">&laquo;</a>
                    {% else %}
                        <a disabled="disabled">&laquo;</a>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <span>{{ i }}</span>
                        {% else %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="next">&raquo;</a>
                    {% else %}
                        <a disabled="disabled">&raquo;</a>
                    {% endif %}
                </nav>
            </section>
        {% else %}
            <center class="col-span-4"><h1
                    class="text-gray-500 font-bold">{% trans "There is no item to display!" %}</h1></center>
        {% endif %}
    </div>
{% endblock %}
{% block click_item %}{% endblock %}

templates/landing/shop.html
{% extends "landing/base.html" %}
{% load i18n %}
{% block title %}{% trans "Home" %}{% endblock %}