DevHelp_DjangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="landing/shop.html"), name="home"),
    path('', include("settings.urls")),
    path('admin/', admin.site.urls),
    path('account/', include("account.urls"), name="account"),
    path('core/', include("core.urls"), name="core"),
    path('cart/', include("order.urls"), name="cart"),
    path('products/', include("products.urls"), name="products"),
    path('category/', include("category.urls"), name="category"),
    path('api/', include("api.urls"), name="api"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from .views import *

app_name = "api"
urlpatterns = [
    # Account
    path('comments/list', CommentListView.as_view(), name='comment_list'),
    path('comments/create', CommentCreateView.as_view(), name='comment_create'),
    path('comments/details/<int:pk>', CommentDetailView.as_view(), name='comment_detail'),
    # Category
    path('categories/', CategoryListView.as_view()),
    path('categories/detail/<slug:url>', CategoryDetailView.as_view()),
    # Core
    path('users/', UserListView.as_view()),
    path('users/detail/<int:pk>', UserDetailView.as_view(), name="user_detail"),
    path('users/passwords/update/<int:pk>', ChangePasswordView.as_view(), name="change_password"),
    path('addresses/', AddressListView.as_view(), name="address"),
    path('addresses/detail/<int:pk>', AddressDetailView.as_view()),
    # Order
    path('orders/', OrderListView.as_view(), name="orders"),
    path('orders/detail/<int:pk>', OrderDetailView.as_view()),
    path('orderitems/', OrderItemListView.as_view(), name="orderitems"),
    path('orderitems/detail/<int:pk>', OrderItemDetailView.as_view(), name="orderitems_detail"),
    # Products
    path('products/', ProductListView.as_view(), name="products"),
    path('products/detail/<slug:url>', ProductDetailView.as_view()),
    path('discounts/', DiscountListView.as_view()),
    path('discounts/detail/<int:pk>', DiscountDetailView.as_view()),
    path('offcodes/', OffCodeListView.as_view()),
    path('offcodes/detail/<str:code>', OffCodeDetailView.as_view(), name="offcode_detail"),
    # Contact
    path('contacts/', ContactCreateListView.as_view(), name="contact"),
]

category/urls.py
from django.urls import path
from .views import CategoryProductShow, Categories

urlpatterns = [
    path('<slug:url>', CategoryProductShow.as_view(), name="category"),
    path('lists/', Categories.as_view(), name="categories"),
]

category/models.py
from django.db import models
from core.models import LogicalModel, TimeStampMixin
from django.utils.translation import gettext_lazy as _, get_language
from core.utils import *


class Category(LogicalModel, TimeStampMixin):
    name_fa = models.CharField(
        max_length=150,
        verbose_name=_("Category FA Name"),
        help_text=_("This is persian name category item"),
        unique=True,
    )
    name_en = models.CharField(
        max_length=150,
        verbose_name=_("Category EN Name"),
        help_text=_("This is english name category item"),
        unique=True,
    )
    image = models.ImageField(
        upload_to=Controllers.Image.img_renamer, null=True, blank=True,
        verbose_name=_("Category image"),
        help_text=_("This is image of category item")
    )
    url = models.SlugField(unique=True, verbose_name=_("Link"),
                           help_text=_("This is url or link of category -> /category/'url'"))
    description_en = models.TextField(
        default="This is test english category description", blank=True, null=True,
        verbose_name=_("English description"),
        help_text=_("This is english description for this category"))
    description_fa = models.TextField(
        default="این متن تست برای توضیحات بخش دسته بندی است", blank=True, null=True,
        verbose_name=_("Persian description"),
        help_text=_("This is persian description for this category"))

    @property
    def description(self):
        return self.description_en if get_language() == "en-US" else self.description_fa

    @property
    def name(self):
        return self.name_en if get_language() == "en-US" else self.name_fa

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name

category/views.py
from django.views.generic import ListView
from category.models import Category
from products.models import Product


class CategoryProductShow(ListView):
    template_name = "landing/products_no_offer.html"
    paginate_by = 8

    def get_queryset(self):
        category_url = self.kwargs['url']
        return Product.objects.filter(category__url=category_url)

    def get_context_data(self, *args, object_list=None, **kwargs):
        kwargs["category"] = Category.objects.filter(url=self.kwargs["url"]).first()
        kwargs["title_page"] = Category.objects.filter(url=self.kwargs["url"]).first().name
        return super().get_context_data(object_list=object_list, **kwargs)


class Categories(ListView):
    template_name = "landing/categories.html"
    queryset = Category.objects.all()
    paginate_by = 4

templates/landing/partial/category.html
{% load i18n %}
<div class="mx-auto max-w-screen-lg w-11/12">
    {% if categories %}
        <div class="mostly-views trs-all-300 grid grid-cols-6 sm:{% if categories|length < 12 %}grid-cols-6 gap-8{% else %}grid-cols-12 gap-4{% endif %} relative rounded-md overflow-hidden py-4">
            <div timer="3000" timer-dot="1000"
                 class="col-span-6 sm:col-span-12 flex absolute bg-gray-900 irsans-b inset-0 text-white items-center justify-center my-4 rounded bg-opacity-95 text-sm sm:text-lg md:text-xl">
                {% trans "Uploading the latest categories" %}
            </div>
            {% for cat in categories %}
                <a hover-class="animate__animated animate__jello animate__infinite" title="{{ cat.name }}"
                   href="{% url "category" cat.url %}">
                    <img src="{{ cat.image.url }}" alt="{{ cat.name_en }}" class="rounded">
                </a>
            {% endfor %}
        </div>
    {% else %}
        <h1 class="py-2 text-gray-500 text-center text-shadow-md font-bold">{% trans "There are no categories to display !" %}</h1>
    {% endif %}
</div>

templates/landing/partial/footer.html
{% load i18n %}
{% get_current_language as lang %}
<div class="trs-all-300 grid grid-cols-1 bg-black bg-opacity-70 text-white px-4 sm:grid-cols-2 max-w-screen-lg relative mx-auto w-11/12 gap-4 rounded-t-lg overflow-hidden py-4">
    <div class="">
        <h6>{{ footer_msg }}</h6>
    </div>
    <div class="{% if lang == "en-US" %}text-right{% else %}text-left{% endif %}">
        {% for s in sochials %}
            <a href="{{ s.url }}" title="{{ s.name }}" class="w-6 inline-block text-center"><i class="gb {{ s.gb_ico }}"></i></a>
        {% endfor %}
    </div>
</div>

templates/landing/partial/header.html
{% load i18n %}
<header class="flex justify-center items-center text-shadow-header">
    <span class="title">
        <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg"><path class="color-change-2x"
                                                                            d="M47.5,-57.3C58.6,-47.3,62.5,-29.5,66,-11.4C69.4,6.6,72.2,25,66.7,42.3C61.2,59.6,47.4,75.9,31.1,79C14.8,82.1,-3.9,72.1,-22.5,64.3C-41.1,56.5,-59.6,50.8,-70.5,37.9C-81.4,24.9,-84.6,4.7,-78.8,-11.5C-73,-27.6,-58.3,-39.8,-43.7,-49.1C-29.1,-58.5,-14.5,-65,1.8,-67.2C18.2,-69.4,36.4,-67.3,47.5,-57.3Z"
                                                                            transform="translate(100 100)"/></svg>
        <a href="{% url "home" %}"><span class="text-white">{{ site.title }} <i class="super-span irsans-b">{{ site.sub_title }}</i></span></a>
    </span>
    <span class="content mr-2 bold color-change-2x trs-all-300">
        <span class="text-sm sm:text-2xl">{{ site.short_description }}</span>
            <a href="{% url "contact" %}" title="{% trans "Contact us" %}" hover-class="animate__animated animate__tada"
               class="bg-red-500 border-dashed border border-red-700 ring-2 ring-red-500 w-10 h-10 text-shadow-md rounded-lg text-center flex items-center justify-center absolute left-0 -top-12"
               style="margin-left: 1px;margin-top: -4px"><i class="gb text-white gb_perm_phone_msg gb_s24"></i>
            </a>
            <a href="{% url "about" %}" title="{% trans "About us" %}" hover-class="animate__animated animate__tada"
               class="bg-yellow-400 border-dashed border border-yellow-600 ring-2 ring-yellow-400 w-10 h-10 text-shadow-md rounded-lg text-center flex items-center justify-center absolute left-12 -top-12"
               style="margin-left: 6px;margin-top: -4px"><i class="gb text-white gb_info gb_s24"></i>
            </a>
            <a href="{% url "profile" %}" title="{% trans "Account" %}" hover-class="animate__animated animate__tada"
               class="bg-green-500 border-dashed border border-green-700 ring-2 ring-green-500 w-10 h-10 text-shadow-md rounded-lg text-center flex items-center justify-center absolute left-24 -top-12"
               style="margin-left: 12px;margin-top: -4px"><i class="gb text-white gb_assignment_ind gb_s24"
                                                             style="margin-left: 2px"></i>
            </a>
            <a href="{{ site.url_full }}" class="home-link ltr"><i class="gb mr-2 gb_share mb-1"></i>
                <span class="text-sm sm:text-xl">{{ site.url }}</span><div
                        class="sub-link ">Ver {{ site.version }}</div>
            </a>
        </span>
    <div class="clearfix"></div>
</header>

templates/landing/partial/nav.html
{% load i18n %}
{% get_current_language as lang %}
<nav class="block p-4 mt-4 mb-8 bg-black bg-opacity-20 rounded-md max-w-screen-lg w-11/12 mx-auto {% if lang == "fa-IR" %}Vazir{% endif %} ">
    <div class="float-right mb-4 sm:mb-0">
        <a href="{% url "cart" %}" class="float-right trs-all-300 hover:text-yellow-400 ml-6 text-gray-300 text-shadow-md"><i class="gb gb_local_mall ml-2"></i>{% trans "Cart" %}</a>
        {% if user %}
            <a href="{% url "profile" %}" class="float-right trs-all-300 hover:text-green-400 ml-6 text-gray-300 text-shadow-md"><i class="gb gb_assignment ml-2"></i>{% trans "Profile" %}</a>
            <a href="{% url "logout" %}" class="float-right trs-all-300 hover:text-red-400 ml-6 text-gray-300 text-shadow-md"><i class="gb gb_close ml-2"></i>{% trans "Logout" %}</a>
        {% endif %}
    </div>
    <div class="float-left">
        {% if user %}
            <span class="float-left text-gray-300 text-shadow-md">{{ user }}<i class="gb gb_account_box mr-2"></i></span>
        {% else %}
            <span class="float-right trs-all-300 text-gray-300 text-shadow-md"><i class="gb gb_lock_open ml-1"></i>
                <a class="trs-all-300 hover:text-pink-400" href="{% url "login" %}">{% trans "Login" %}</a>
                <i class="gb mx-1">/</i>
                <a class="trs-all-300 hover:text-blue-400" href="{% url "register" %}">{% trans "Register" %}</a>
            </span>
        {% endif %}
    </div>
    <div class="clearfix"></div>
</nav>

templates/landing/partial/offer.html
{% load i18n %}
{% get_current_language as lang %}
<div class="relative mt-1 mb-8 max-w-screen-lg w-11/12 mx-auto">
    <div class="rtl py-6 sm:py-2 md:py-4 grid grid-cols-1 sm:grid-cols-3 gap-8 sm:gap-4 md:gap-8">
        {% for item in offers %}
            <a hover-class="anim-shadowly" href="{% url "product" item.url %}"
               class="relative bg-black bg-opacity-40 bg-strip-sm rounded-lg">
                <div class="ribbon ribbon-r"><span>{% trans "Special sale" %}</span></div>
                <div class="relative">
                    <img src="{{ item.image.default }}" alt="{{ item.title_en }}"
                         class="border-8 border-red-500 rounded-t-lg">
                    <h3 class="yekan-b absolute bg-black trs-all-300 bg-opacity-70 text-white text-2xl sm:text-sm md:text-lg lg:text-2xl pr-2 pl-5 sm:py-1 lg:py-2 py-2 bottom-0 right-0 rounded-tl-3xl">{{ item.title }}</h3>
                </div>
                <p class="p-4 text-justify text-white sm:text-sm">{{ item.short_description }}</p>
                <div class="bg-black relative bg-strip-sm bg-opacity-30 text-center p-4 rounded-b-lg">
                <span class="absolute text-2xl sm:text-sm md:text-lg right-4 {% if lang != "en-US" %}Vazir{% endif %} {% if item.discount_count %}md:bottom-3 bottom-3{% else %}md:bottom-6 bottom-7{% endif %} text-gray-400">
                    <span class="block">{% trans "Toman" %}</span>
                    {% if item.discount_count %}
                        <span class="line-through">{{ item.price }}</span>
                    {% endif %}
                </span>
                    <b class="text-5xl sm:text-2xl md:text-4xl mt-2 sm:mt-0 block text-left text-pink-700 text-shadow-md {% if lang != "en-US" %}Vazir{% endif %}">{{ item.final_price }}</b>
                </div>
            </a>
        {% endfor %}
    </div>
</div>

templates/landing/partial/search.html
{% load static %}
{% load i18n %}
{% get_current_language as lang %}
<form class="mt-8 mb-4 mx-auto max-w-screen-lg trs-all-300 w-11/12 relative">
    <div id="spiner-search" class="absolute inset-0 flex justify-center trs-all-300 items-center invisible z-30">
        <i class="gb block text-5xl gb_cached gb_animate_spin text-white text-shadow-md"></i>
    </div>
    <div id="filter-search" class="grid grid-cols-12 gap-0 w-full trs-all-300 z-20 filter relative">
        <label for="search"
               class="col-span-2 md:col-span-1 bg-white bg-opacity-10 {% if lang == "en-US" %}rounded-l-md{% else %}rounded-r-md{% endif %}  text-white text-center leading-10 px-3 py-2">
            <i class="gb gb_search gb_s36"></i>
        </label>
        <input id="search" type="text" placeholder="{% trans "Search" %} ..."
               class="col-span-10 md:col-span-11 search-bar-input leading-10 relative text-white irsans-b bg-white bg-opacity-10 text-2xl px-4 pb-4  {% if lang == "en-US" %}border-l-4 rounded-r-md{% else %}rounded-l-md border-r-4{% endif %} ">
        <div id="search_box" class="col-span-12 relative -top-4 hidden">
            <div class="w-full p-4">
                <div class="bg-white rounded-b-md bg-opacity-10 p-4 pb-1">
                </div>
            </div>
        </div>
    </div>
</form>
<script>

    window.addEventListener('keydown',function(e){if(e.keyIdentifier=='U+000A'||e.keyIdentifier=='Enter'||e.keyCode==13){if(e.target.nodeName=='INPUT'&&e.target.type=='text'){e.preventDefault();return false;}}},true);


    $("#search").on("input", function () {
        const spiner = $("#spiner-search")
        const filter = $("#filter-search")
        let search_box = $("#search_box")
        $is_empty = true
        const len = $(this).val().length

        if (len >= 3) {
            const value = $(this).val().toLowerCase()

            // add blur filter
            filter.addClass("blur-sm")
            spiner.removeClass("invisible")

            // show main box
            search_box.removeClass("hidden").removeClass("animate__animated animate__fadeOut").addClass("animate__animated animate__fadeIn")
            search_box.children("div").children("div").html('')

            // get product list :
            $.getJSON("{% url "api:products" %}", function (data) {
                search_box.children("div").children("div").html('')
                $.each(data, function (k, v) {

                    // product
                    if (v["title_en"].toLowerCase().includes(value) || v["title_fa"].toLowerCase().includes(value)) {
                        $is_empty = false

                        search_box.children("div").children("div").append(
                            '<a href="' + v["product_url"] + '" class="item-search bg-black grid grid-cols-12 rounded-md mb-4 w-full bg-opacity-10 p-4 hover:bg-opacity-20 trs-all-300">' +
                            '<img src="' + v["image"] + '" class="{% if lang == "en-US" %}float-left{% else %}float-right{% endif %} col-span-3 rounded-md" style="height: 100%">' +
                            '<div class="{% if lang == "en-US" %}float-left ml-6{% else %}float-right mr-6{% endif %} inline col-span-9">' +
                            '<h1 class="Vazir font-bold text-shadow-md text-xl text-white">' + v["title"] + '</h1>' +
                            '<p class="{% if lang == "en-US" %}float-left{% else %}float-right{% endif %} text-gray-300 irsans-b">{% trans "Category" %} : ' + v["category"]["name"] + '</p>' +
                            '<br><br>' +
                            '<p class="Vazir text-gray-300">' + v['short_description'] + '</p>' +
                            '</div>' +
                            '</a>'
                        )
                    }

                    // category :
                    if (v["category"]["name_en"].toLowerCase().includes(value) || v["category"]["name_fa"].toLowerCase().includes(value)) {
                    }
                })

                if ($is_empty) {
                    search_box.children("div").children("div").html('')
                    search_box.children("div").children("div").prepend(
                        '<a class="bg-black grid grid-cols-12 rounded-md mb-4 w-full bg-opacity-10 p-4 trs-all-300 text-center">' +
                        '<h1 class="Vazir col-span-12 font-bold text-shadow-md text-2xl text-white">{% trans "Nothing found :(" %}</h1>' +
                        '</a>'
                    )
                }
            })
            $(document).ajaxStop(function () {
                filter.removeClass("blur-sm")
                spiner.addClass('invisible')
            })
        }

        // empty :
        if (len === 0) {
            search_box.removeClass("animate__animated animate__fadeIn").addClass("animate__animated animate__fadeOut")
            setTimeout(function () {
                search_box.addClass("hidden")
            }, 700)
        }
    })
</script>